
 
记录时间：2015-11-16 20:29:27,544 
线程ID:[5] 
日志级别：  ERROR 
错误描述：
                请求【DictController】的【GetBPDescription】产生异常：
                Action参数：pclsCache=&SBP=180
               Http请求头:Connection: keep-alive
Accept: */*
Accept-Encoding: gzip, deflate, sdch
Accept-Language: zh-CN, zh; q=0.8
Cookie: state-C91E0DB9-C9C3-4E43-A3B8-CC90820A46FD=SYSEXP%3A1; Username=UnknownUser
Host: localhost:7516
Referer: http://localhost:7516/Help/Api/GET-Api-v1-Dict-BPDescription_SBP
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36

                客户端IP：::1,
                HttpMethod:GET
                    
 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 CDMISrestful.DataMethod.DictMethod.GetBPDescription(DataConnection pclsCache, Int32 SBP) 位置 c:\Users\syf\Desktop\CDMISrestful\CDMISrestful\DataMethod\DictMethod.cs:行号 639
   在 CDMISrestful.Models.DictRepository.GetBPDescription(DataConnection pclsCache, Int32 SBP) 位置 c:\Users\syf\Desktop\CDMISrestful\CDMISrestful\Models\DictRepository.cs:行号 129
   在 CDMISrestful.Controllers.DictController.GetBPDescription(DataConnection pclsCache, Int32 SBP) 位置 c:\Users\syf\Desktop\CDMISrestful\CDMISrestful\Controllers\DictController.cs:行号 153
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()

 
记录时间：2015-11-16 20:44:46,002 
线程ID:[15] 
日志级别：  ERROR 
错误描述：
                请求【RiskInfoController】的【GetRiskInput】产生异常：
                Action参数：UserId={UserId}
               Http请求头:Connection: keep-alive
Accept: */*
Accept-Encoding: gzip, deflate, sdch
Accept-Language: zh-CN, zh; q=0.8
Cookie: state-C91E0DB9-C9C3-4E43-A3B8-CC90820A46FD=SYSEXP%3A1; Username=UnknownUser
Host: localhost:7516
Referer: http://localhost:7516/Help/Api/GET-Api-v1-RiskInfo-RiskInput_UserId
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36

                客户端IP：::1,
                HttpMethod:GET
                    
 
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 CDMISrestful.Models.RiskInfoRepository.GetRiskInput(DataConnection pclsCache, String UserId) 位置 c:\Users\syf\Desktop\CDMISrestful\CDMISrestful\Models\RiskInfoRepository.cs:行号 997
   在 CDMISrestful.Controllers.RiskInfoController.GetRiskInput(String UserId) 位置 c:\Users\syf\Desktop\CDMISrestful\CDMISrestful\Controllers\RiskInfoController.cs:行号 76
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
