
 
记录时间：2015-11-17 21:13:48,207 
线程ID:[7] 
日志级别：  ERROR 
错误描述：
                请求【RiskInfoController】的【GetM1Risk】产生异常：
                Action参数：UserId=PID201511170001
               Http请求头:Connection: keep-alive
Accept: */*
Accept-Encoding: gzip, deflate, sdch
Accept-Language: zh-CN, zh; q=0.8
Host: localhost:7516
Referer: http://localhost:7516/Help/Api/GET-Api-v1-RiskInfo-M1Risk_UserId
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2427.7 Safari/537.36

                客户端IP：::1,
                HttpMethod:GET
                    
 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 CDMISrestful.Models.RiskInfoRepository.GetM1RiskInput(DataConnection pclsCache, String UserId) 位置 f:\Work\chronic disease management\github\CDMISrestful\CDMISrestful\Models\RiskInfoRepository.cs:行号 1364
   在 CDMISrestful.Models.RiskInfoRepository.GetM1Risk(DataConnection pclsCache, String UserId) 位置 f:\Work\chronic disease management\github\CDMISrestful\CDMISrestful\Models\RiskInfoRepository.cs:行号 76
   在 CDMISrestful.Controllers.RiskInfoController.GetM1Risk(String UserId) 位置 f:\Work\chronic disease management\github\CDMISrestful\CDMISrestful\Controllers\RiskInfoController.cs:行号 76
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
